# Generated by Django 3.0.4 on 2020-03-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Fun', 'Fundacja'), ('Org', 'Organizacja pozarządowa'), ('Zb', 'Zbiórka lokalna')], default='Fun', max_length=3)),
            ],
        ),
    ]
