# Generated by Django 3.0.4 on 2020-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_clothes', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
