# Generated by Django 3.0.4 on 2020-03-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_clothes', '0006_institution_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
