# Generated by Django 3.0.4 on 2020-03-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_clothes', '0007_auto_20200314_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(null=True, verbose_name='Dar odebrany'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='share_clothes.Category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('Fun', 'Fundacja'), ('Org', 'Organizacja pozarządowa'), ('Zb', 'Zbiórka lokalna')], default='Fun', max_length=3, verbose_name='Typ organizacji'),
        ),
    ]
